POST http://localhost:5000/api/location
Content-Type: application/json

{
    "city": "jalal", 
    "region": "dob"
}

###
POST http://localhost:5000/api/university
Content-Type: application/json

{

}

###
POST http://localhost:5000/api/joinuniv
Content-Type: application/json