POST http://localhost:5000/api/location
Content-Type: application/json

{
    "region": "dob",
    "city": "fdd", 
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    
    "first_name": "mohahamozayani",
    "last_name": "lkhattabi",
    "username": "usernaem1234",
    "birth_date": '1000-01-01',
    "level": "bac+5",
    "about": "is\/here\/samawi",
    "password": "1234",
    "account_type": "teacher",
    "gender": 1,
    "email": "hamidoimotnadih@gmail.com",
    "phone": 06254242,
    "status": "active",
    "profile_url": "http://someurl",
    "background_url": "http://someurl",
    "left_at": null,
    
}


###
GET http://localhost:5000/api/register


###
http://localhost:5000/


###
POST http://localhost:5000/api/auth/register
Content-Type: application/json